### ISSUE TITLE
libsquash0.8.dll not found

### ISSUE THREAD

**Issue by michaelbaisch** [elliotwoods/ofxSquash#12]
When running the `exampleStreamSimple` example on Windows 8.1, it tells me that `libsquash0.8.dll` cannot be found. I can simply confirm (OK) this twice and it runs and works anyway. I couldn't figure out why squash wants that dll and isn't satisfied with the `squash0.8.dll` in the `bin` folder. 
What I could figure out is that it happens when in the `getCodecList()` function this
```
squash_foreach_codec(populateCodecListCallback, &codecs);
```
is called.
Any idea how to fix this?

**Comment by elliotwoods** [comment]
hey michael!
my guess is that the codecs which we had to build with mingw use a
different naming convention from the ones we built in VS
please try removing some codecs from the plugins folder and see if you
still get the same error
e.g. move half of them out, check, then try moving another half of what's
left out, etc until you find the plugins causing the issue
chances are it's not a codec that you need

i haven't had the error here in production use sorry
but i haven't run the examples for a while

**Comment by michaelbaisch** [comment]
You were right, moving the right codec folders somewhere else did the trick.
The responsible codec folders are: `gipfeli`, `zlib`, and `zlib-ng`.
