### ISSUE TITLE
OSX supported version / architecture?

### ISSUE THREAD

**Issue by satoruhiga** [elliotwoods/ofxSquash#3]
I'm trying to rebuild OSX libs. but some problem occurred
1. snappy plugin can not build on 10.7 SDK
   I'm not sure but around OSX 10.8 clang changes c++ runtime. so I can't build in this time.
   maybe I can do it if took a time, but I think we need discuss about OSX supported version and architecture.
2. universal binary?
   Also, in this time I did build only for 64bit. but sometimes we need 32bit.
   In technically, I think possible it is 

libs is here  http://cl.ly/2W0e001F1N46

**Comment by elliotwoods** [comment]
I think we can say 10.8+ is supported. I've had other issues with oF pre-10.8

Universal library would be good, but not really a "must have" feature.

**Comment by elliotwoods** [comment]
@satoruhiga - the libs in the zip fix some of the previous issues?
should we replace the libs in the repo with these new libs?

**Comment by satoruhiga** [comment]
I rebuild osx libs! (currently x64 only)

https://github.com/satoruhiga/ofxSquash/commit/fb580ae6c54cb3a6a5d98e9a81411c4c3f5b4099

**Comment by elliotwoods** [comment]
checked out your branch on osx

testing in debug
![image](https://cloud.githubusercontent.com/assets/328294/13563977/77d47890-e489-11e5-857a-e8752180ca27.png)

testing in release
![image](https://cloud.githubusercontent.com/assets/328294/13564060/0fece09a-e48a-11e5-81c4-d4793824ff44.png)

works for me!
satoru of death is gone :)

32bit too is ideal, 
but you must be busy with other things

**Comment by elliotwoods** [comment]
merged e0faa09f535884454b570d2a38469357335aff07
